services:
  - type: web
    name: uno-multiplayer
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
